### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kajmagnus** [zimbatm/hostnames-and-usernames-to-reserve#3]
Would you please like to somewhere clarify under which license the list of usernames is licensed?

Thanks & regards

**Comment by zimbatm** [comment]
I'm licensing the work under the CC0, effectively making it public domain. See https://github.com/zimbatm/hostnames-and-usernames-to-reserve/commit/e21c395fd0f371cd09b8b19f5f40d593d092a173

**Comment by kajmagnus** [comment]
Ok thanks for the info :- )
